name: Run flow.sh and Push Changes to Dev

on:
  push:
    branches:
      - 'main'  # Trigger only on push to main branch
    paths:
      - 'img/**'

permissions:
  contents: write  # Explicitly set the permission to allow pushing to the repository

jobs:
  run-and-push:
    if: github.actor != 'actions-user'  # Only run if the last commit author is not 'actions-user'
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can create new branches if needed

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Ensure dev branch exists
      run: |
        if git rev-parse --verify dev; then
          git checkout dev
        else
          git checkout -b dev
        fi

    - name: Pull latest changes from dev branch
      run: |
        git pull origin dev --rebase

    - name: Make flow.sh executable
      run: chmod +x ./flow.sh

    - name: Run flow.sh
      run: ./flow.sh

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Automated changes by GitHub Actions"
        git push origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge Dev into Main
      run: |
        git checkout main
        git pull origin main --rebase
        git merge dev --no-ff -m "Merge changes from dev into main"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
