name: Run flow.sh and Push Changes to Dev

on:
  push:
    branches:
      - 'main'  # Trigger on push to any branch

permissions:
  contents: write  # Explicitly set the permission to allow pushing to the repository

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can create new branches if needed

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Ensure dev branch exists
      run: |
        if git rev-parse --verify dev; then
          git checkout dev
        else
          git checkout -b dev
        fi

    - name: Make flow.sh executable
      run: chmod +x ./flow.sh

    - name: Run flow.sh
      run: ./flow.sh

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Automated changes by GitHub Actions"
        git push origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
